
POST https://simhost-084712371141e3e4a.agni.secondlife.io:12043/cap/eebb076f-b314-3069-5cf5-2383a0345ab8
Authorization: Bearer 123

{
  "deliveryOrder": {
    "customerKey": "b5ab83d9-032c-4013-b10a-1dbf92245ee7",
    "inventoryName": "How to resize a ball",
    "orderAmount": 50
  }
}

###

POST https://simhost-084712371141e3e4a.agni.secondlife.io:12043/cap/eebb076f-b314-3069-5cf5-2383a0345ab8
Authorization: Bearer 123

ping

###