#
# Add your Warehouse's URL to test.
# If you need to test on a local environment, for instance if you are running
# OpenSimulator, you will also have to work with non-secure URL: http://
#

POST https://...
Authorization: Bearer 123

{
  "deliveryOrder": {
    "customerKey": "test-avatar-uuid",
    "inventoryName": "inventory-name"
  }
}

###

POST https://...
Authorization: Bearer 123

ping

###
